const categories = [
  "All Categories",
  "Aerospace",
  "Agritech",
  "Art and Design",
  "Automotive",
  "Banking",
  "Beauty and Wellness",
  "Biotechnology",
  "Communication",
  "Construction",
  "Consulting",
  "CRM",
  "E-commerce",
  "Education",
  "Energy",
  "Environmental",
  "Fashion",
  "Financial Services",
  "Fitness",
  "Food and Beverage",
  "Government",
  "Healthcare",
  "Hospitality",
  "ICT",
  "Insurance",
  "Legal",
  "Logistics",
  "Manufacturing",
  "Marketing",
  "Media and Entertainment",
  "Nonprofit",
  "Pharmaceutical",
  "Real Estate",
  "Research",
  "Retail",
  "Security",
  "Social Services",
  "Software",
  "Sports",
  "Startups",
  "Technology",
  "Telecommunications",
  "Telecom",
  "Tourism",
  "Transportation",
  "Travel",
  "Utilities",
] as const;

export default categories;
