const categories = [
  "Agritech",
  "Financial Services",
  "Software",
  "ICT",
  "CRM",
  "Marketing",
  "Communication",
  "Banking",
  "Healthcare",
  "Retail",
  "Education",
  "E-commerce",
  "Automotive",
  "Media and Entertainment",
  "Real Estate",
  "Travel and Tourism",
  "Food and Beverage",
  "Energy",
  "Telecommunications",
  "Manufacturing",
  "Fashion",
  "Sports",
  "Art and Design",
  "Nonprofit",
  "Government",
  "Transportation",
  "Construction",
  "Consulting",
  "Hospitality",
  "Insurance",
  "Technology",
  "Startups",
  "Pharmaceutical",
  "Biotechnology",
  "Research",
  "Logistics",
  "Environmental",
  "Utilities",
  "Aerospace",
  "Fitness",
  "Beauty and Wellness",
  "Legal",
  "Security",
  "Telecom",
  "Social Services",
  "Other",
] as const;

export default categories;
